
import React from 'react';
import { Link } from 'react-router-dom';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-remixr-dark text-white">
      <Header />
      
      <main className="pt-32 pb-16 px-4">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8 gradient-text">Terms and Conditions</h1>
          
          <div className="prose prose-invert max-w-none">
            <p className="text-white/70 mb-6">
              Last updated: April 26, 2024
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">1. Acceptance of Terms</h2>
            <p className="text-white/70 mb-4">
              By downloading, installing, or using Remixr ("the App"), you agree to be bound by these Terms and Conditions ("Terms"). 
              If you do not agree to these Terms, please do not use the App.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">2. License</h2>
            <p className="text-white/70 mb-4">
              Remixr grants you a limited, non-exclusive, non-transferable, revocable license to use the App for your personal, 
              non-commercial purposes. You may not copy, modify, distribute, sell, or lease any part of the App or its content.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">3. User Conduct</h2>
            <p className="text-white/70 mb-4">
              You agree not to use the App to:
            </p>
            <ul className="list-disc pl-8 mb-4 text-white/70 space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe the intellectual property rights of others</li>
              <li>Upload or share inappropriate, offensive, or illegal content</li>
              <li>Attempt to gain unauthorized access to the App's systems or networks</li>
              <li>Use the App in any way that could damage, disable, or impair its functionality</li>
            </ul>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">4. Intellectual Property Rights</h2>
            <p className="text-white/70 mb-4">
              The App and its content, features, and functionality are owned by Remixr and are protected by copyright, 
              trademark, and other intellectual property laws. You retain ownership of the images you upload to the App. 
              You own the output images generated by the App based on your inputs.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">5. Remixr Pro Subscription</h2>
            <p className="text-white/70 mb-4">
              Remixr Pro is a subscription service that provides enhanced features. Subscription fees are charged on a 
              recurring basis according to your selected plan. You can cancel your subscription at any time through your 
              app store account settings. No refunds will be provided for any unused portion of a subscription period.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">6. Disclaimers</h2>
            <p className="text-white/70 mb-4">
              The App is provided "as is" without warranties of any kind, either express or implied. Remixr does not 
              guarantee that the App will always be secure, error-free, or available at all times. We are not responsible 
              for any content generated by the App that may be deemed inappropriate or offensive.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">7. Limitation of Liability</h2>
            <p className="text-white/70 mb-4">
              To the maximum extent permitted by law, Remixr shall not be liable for any indirect, incidental, 
              special, consequential, or punitive damages resulting from your use of or inability to use the App.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">8. Termination</h2>
            <p className="text-white/70 mb-4">
              Remixr may terminate or suspend your access to the App immediately, without prior notice, for conduct 
              that we believe violates these Terms or is harmful to other users, us, or third parties, or for any 
              other reason at our sole discretion.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">9. Governing Law</h2>
            <p className="text-white/70 mb-4">
              These Terms shall be governed by and construed in accordance with the laws of the United States, 
              without regard to its conflict of law provisions.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">10. Changes to Terms</h2>
            <p className="text-white/70 mb-4">
              We may modify these Terms at any time by posting the revised terms on our website or within the App. 
              Your continued use of the App after any such changes constitutes your acceptance of the new Terms.
            </p>
            
            <h2 className="text-2xl font-semibold mt-8 mb-4">11. Contact Us</h2>
            <p className="text-white/70 mb-4">
              If you have any questions about these Terms, please contact us at support@remixrapp.com.
            </p>
            
            <div className="mt-12 mb-8">
              <Link to="/" className="text-remixr-magenta hover:text-white transition-colors">
                &larr; Back to Home
              </Link>
            </div>
          </div>
        </div>
      </main>
      
      <Footer />
    </div>
  );
}
